### ISSUE TITLE
Lack of package.json

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#10]
I would recomend to create a package.json file, with the dependency in them so that a node server can be easily installed using the command:

- npm install

**Comment by segallagher** [comment]
package.json added

**Comment by Willg3D** [comment]
The package.json does not have your node server dependencies listed.

**Comment by segallagher** [comment]
it should have the dependencies now

**Comment by Willg3D** [comment]
I agree there is now a package.json with needed dependencies.
