### ISSUE TITLE
Usernames can have spaces

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#11]
I'm not too sure if this was a requirement or not. Usernames probably should not allow spaces.

**Comment by segallagher** [comment]
disallowed whitespace

**Comment by Willg3D** [comment]
While the issue seems to be mostly resolved, nothing informs me that the space in the username text field is causing an issue. Some sort of feedback for spaces being the cause of a failed account creation submission would be appreciated.

**Comment by segallagher** [comment]
I added indication that spaces are not allowed in usernames or passwords

**Comment by Willg3D** [comment]
Works great! Approved.
