### ISSUE TITLE
Variable obj in app.js

### ISSUE THREAD

**Issue by nidamon** [bfforsythe/NotFlix#14]
Variable names:
        var "obj" line 119 could be newMovie instead
	var "obj" could be more descriptive on line 204 and 210
	var "obj" could be more descriptive on line 219 and 225

Commenting
        line 381 commented out code

**Comment by segallagher** [comment]
made the changes

**Comment by nidamon** [comment]
You missed the 119 obj but otherwise good. You can close this when you want.

**Comment by segallagher** [comment]
changed the 119 obj this time
