### ISSUE TITLE
Hardcoded Numbers in code

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#16]
Hardcoded Numbers:
- loginSuccess.ejs uses hardcoded width and height for each function
- In loginSuccess.ejs, function checkActivity, line 54 hardcoded 10000
- In browsingPage.ejs, harcoded values line 32, 34, 36, 51, 53, 55, 70, 72, and 74

**Comment by bfforsythe** [comment]
modularized stuff, removed hardcoded values

**Comment by Willg3D** [comment]
@akdasUAF
