### ISSUE TITLE
Repetitive Code

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#18]
Repetitive Code:
- stylesheet.css is not used at all (as far as I can tell

**Comment by Willg3D** [comment]
I also forgot to mention
- In browsingPage.ejs repeated code for each genre starting line 30 and 78
They use essentially the same exact code, but with only different names for each genre.

**Comment by bfforsythe** [comment]
stylesheet? more like styleyeet (removed stylesheet as it is unused.)

modularity for slideshows at this point in time would require implementing an entire library for carousels, unfortunately the current version is the only way this implementation will work.

**Comment by Willg3D** [comment]
Acceptable

**Comment by Willg3D** [comment]
@akdasUAF will discuss in the next lecture
