### ISSUE TITLE
Text Search Bar Request

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#19]
I want to be able to search for a video by title instead of just genre. All the search bar would need to do is reduce what video can be seen based on the text search being a subset string of the title of any video.

**Comment by nidamon** [comment]
If you intend to try it out, this is a great starting point: https://stackoverflow.com/questions/38392666/mongo-find-by-substring-in-any-field

**Comment by bfforsythe** [comment]
* top middle of page for search
* hide carousel, show results
*

**Comment by Willg3D** [comment]
- Search bar on top of the page (placement not important, can be left, middle, or right)
- Have the genre list be dynamic instead of fixed. (This will also mean editing the video upload page)
- Have a button to clear the search next to the search bar.
- The carousels can be hidden or can be shown. (Really, just making a separate temp page with results works, but not necessary)

**Comment by bfforsythe** [comment]
text search works now! still working on dynamically adding carousels.

* Search bar is now in the middle of the top of the page
* The clear button works to remove all data inside of the search bar
* The carousels are hidden, at which point the search result is populated into the page.

**Comment by bfforsythe** [comment]
clear button now returns the user to the slideshows, and it has been modularized.
