### ISSUE TITLE
Accounts are not Locked properly

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#4]
When accounts are locked, just refreshing the page allows for new attempts.

**Comment by segallagher** [comment]
Accounts should be locked through mongoDB now

**Comment by Willg3D** [comment]
Can a user get a warning if they have 1 attempt remaining? Other than that the accounts now lock.

**Comment by segallagher** [comment]
There are now warnings that mention how many attempts you have remaining if you provide a valid user

**Comment by Willg3D** [comment]
The issue is fully resolved, and works great.
